name: AutoTest & Pages

on:
  pull_request:
    branches:
      - stable
      - main
  push:
    branches:
      - main
      - stable
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'pnpm'

      - name: Install autotest and build required packages
        run: pnpm -F autotest run setup-local

      - name: Cache Puppeteer browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: ${{ runner.os }}-puppeteer-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Chrome for Puppeteer
        run: pnpm --filter autotest exec puppeteer browsers install chrome

      - name: Record START_TIME
        run: echo "START_TIME=$(date -u '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Set BRANCH_NAME
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Set GITHUB_WORKFLOW_URL
        run: echo "GITHUB_WORKFLOW_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Run mocha in autoTest package
        continue-on-error: true
        run: pnpm --filter autotest run test

      - name: Upload test report artifact
        id: upload_report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autotest-report
          path: packages/autoTest/reports

      - name: Construct artifact download URL
        run: echo "WEBSITE_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload_report.outputs.artifact-id }}" >> $GITHUB_ENV


      - name: Send summary to Lark with page URL
        run: pnpm --filter autotest run post-test
        env:
          WEBSITE_URL: ${{ env.WEBSITE_URL }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          START_TIME: ${{ env.START_TIME }}
          GITHUB_WORKFLOW_URL: ${{ env.GITHUB_WORKFLOW_URL }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          RECEIVE_ID_PRIVATE: ${{ secrets.RECEIVE_ID_PRIVATE }}
          RECEIVE_ID_PUBLIC: ${{ secrets.RECEIVE_ID_PUBLIC }}
