name: CI


on:
  push:
    branches:
      - main
      - stable
  pull_request:

env:
  CI: true
  SKIP_SIMPLE_GIT_HOOKS: 1

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'pnpm'
      
      - name: Install dependencies and build
        run: pnpm run setup
      
      - name: Test
        run: pnpm run test

      - name: Test changeset
        run: npx changeset version
      
      - name: Report legacy status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              context: 'ci/github-actions',      
              description: 'CI passed'
            });
